(load "~/adk/android-sdk-mac_x86/tools/lib/android.el")

(setq mac-command-modifier 'meta)
(setq load-path (cons "~/etc" load-path))
(load "xcscope.el")
(load "mark.el")
(load "sams-lib.el")
(load "text.el")
(load "window.el")
(load "yic-buffer.el")
(load "jtags.el")
(load "jtags-extras.el")
(setq tags-auto-read-changed-tag-files 't)
(require 'git)
(require 'git-blame)
(require 'android)
(require 'xcscope)
(require 'color-theme)

(ansi-color-for-comint-mode-on)
(set-cursor-color "red")
(display-time)
(if (fboundp 'global-font-lock-mode)
    (global-font-lock-mode 1))
(setq transient-mark-mode t)

(add-hook 'LaTeX-mode-hook 'turn-on-reftex) 
(autoload 'matlab-mode "~/etc/matlab.el" "Enter Matlab mode." t)
(setq auto-mode-alist (cons '("\\.m\\'" . matlab-mode) auto-mode-alist))
(autoload 'matlab-shell "~/etc/matlab.el" "Interactive Matlab mode." t)
(add-hook 'java-mode-hook (function cscope:hook))

(color-theme-euphoria)
(load "key.el")
(setq x-select-enable-clipboard t)
