(setq tags-table-list '("/Volumes/android/git/mydroid/frameworks/base/core/java"
			"/Volumes/android/git/mydroid/frameworks/base/drm/java"
			"/Volumes/android/git/mydroid/frameworks/base/graphics/java"
			"/Volumes/android/git/mydroid/frameworks/base/keystore/java"
			"/Volumes/android/git/mydroid/frameworks/base/libs/rs/java"
			"/Volumes/android/git/mydroid/frameworks/base/location/java"
			"/Volumes/android/git/mydroid/frameworks/base/location/lib/java"
			"/Volumes/android/git/mydroid/frameworks/base/media/java"
			"/Volumes/android/git/mydroid/frameworks/base/nfc-extras/java"
			"/Volumes/android/git/mydroid/frameworks/base/opengl/java"
			"/Volumes/android/git/mydroid/frameworks/base/sax/java"
			"/Volumes/android/git/mydroid/frameworks/base/services/java"
			"/Volumes/android/git/mydroid/frameworks/base/telephony/java"
			"/Volumes/android/git/mydroid/frameworks/base/voip/java"
			"/Volumes/android/git/mydroid/frameworks/base/vpn/java"
			"/Volumes/android/git/mydroid/frameworks/base/wifi/java"
			"/Volumes/android/git/mydroid/frameworks/ex/common/java"
                        "/Users/song/src/SkeletonApp"))